<?php
/* ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL); */
session_start();

$randA = mt_rand(1,10);
$randB = mt_rand(1,10);
$randAB = $randA + $randB;
$_SESSION["Math"] = $randA." + ".$randB." = ?";
$_SESSION["randAB"] = $randAB;

include_once ('../config.php');

// getBalance
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $rcp_server);
curl_setopt($ch, CURLOPT_TIMEOUT, 5); //timeout in seconds
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"jsonrpc\": \"2.0\", \"id\": \"test\",\"method\":\"getBalance\"}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Accept: application/json";
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

$data_json = json_decode($result, true);
$availableBalance = $data_json['result']['availableBalance']; // need to divided by coinUnit

if (empty($availableBalance)) {
	$availableBalance = 0;
}

if (curl_errno($ch)) {
    //echo 'Error:' . curl_error($ch); // Hide curl error. You can turn this on for development.
}
curl_close ($ch);
####
$mysqli = new mysqli($sqlIP,$sqluser,$sqlpassword,$sqlDB);
//Output any connection error
if ($mysqli->connect_error) {
    die('Error : ('. $mysqli->connect_errno .') '. $mysqli->connect_error);
}

//MySqli Select Query
$results = $mysqli->query("SELECT * FROM wrkzcoin_faucet ORDER BY id DESC");

$payments = array();
$i = 0;

$totalPayout = 0;
$totalPaid = 0;
while($results && $row = $results->fetch_object()) {
        $payments[$i]['id'] = $row->id;
        $payments[$i]['wallet'] = $row->wallet;
        $payments[$i]['lastDateGet'] = $row->lastDateGet;
        $payments[$i]['lastPaid'] = $row->lastPaid;
		$payments[$i]['Session'] = $row->Session;
        $payments[$i]['lastip'] = $row->lastip;
        $i++;

        $totalPaid = $totalPaid + ($row->lastPaid / $coinUnit); // divided by $coinUnit
}
$mysqli->close();
$totalPayout = count($payments);

?>
<h3><i class="fa fa-money fa-fw" aria-hidden="true"></i> &nbsp; WrkzCoin Faucet <?php if (!empty($availableBalance)) echo ' (remaining '. number_format($availableBalance/$coinUnit, 2) .$coinName.')';?></h3>


<div class="input-group col-md-12">
<div class="row">
	<div class="panel panel-default">
	<div class="panel-heading">
	<h3 class="panel-title"><i class="fa fa-exchange fa-fw" aria-hidden="true"></i> Recent Given Wrkz</h3>
	</div>
	<div class="panel-body">
	<div class="table-responsive">
	<table class="table table-hover" id="mem_pool_table">
	<thead>
	<tr>

	<th width="20%"><i class="fa fa-money"></i> Amount (Wrkz) </th>
	<th width="60%"><i class="fa fa-paw"></i> Hash</th>
	</tr>
	</thead>
	<tbody id="mem_pool_rows">
	<?php
	$x = 0;
	while($x <= 10) {
		if (!empty($payments[$x])) {
			echo "<tr><td>".number_format($payments[$x]['lastPaid']/$coinUnit, 2)."</td><td><a href='?hash=".$payments[$x]['Session']."#blockchain_transaction'>".$payments[$x]['Session']."</a></td></tr>";
		}
		$x++;
	}
	?>
	</table>
	</div>
	</div>
	</div>
</div>
</div>
	
<div class="input-group col-md-12">
<div id="form-container">
<form method ="post" id="faucet-form" >
<div class="form-group">
    <div class="row">
        <label for="mathequation" id="MathChangeHere">Solve this <?php if (!empty($_SESSION["Math"])) echo $_SESSION["Math"];?></label>
        <input class="form-control" name="mathequation" placeholder="Answer Math Equation" id="mathequation" autocomplete="off">
    </div>
	
    <div class="row">
        <label for="WrkzAddress">Your WrkzCoin Address</label>
        <input class="form-control" name="WrkzAddress" placeholder="98 char public WrkzCoin address" id="WrkzAddress">

    </div>
</div>

    <div class="row">
        <button class="btn btn-primary" type="submit">
            <span class="fa fa-money"></span> &nbsp; Get WrkzCoin
        </button>
    </div>
</form>
</div>

<div class="row">
<div class="col-sm-6 stats">
<div id="addressError"><?php if (isset($_POST['public_address'])) echo "haha";?></div>
</div>
</div>

</div>

<script>
$('#faucet-form').submit(function(e){
    e.preventDefault(); // Prevent Default Submission
    $.ajax({
    url: 'givemeWrkz.php',
    type: 'POST',
    data: $(this).serialize(), // it will serialize the form data
        dataType: 'json',
		async: false,
    })
    .done(function(data){
        if (data && data.res1 && data.res2) {
			$('#MathChangeHere').fadeOut('slow', function(){
				 $('#MathChangeHere').fadeIn('slow').html(data.res1);
			});
			$('#addressError').fadeOut('slow', function(){
				 $('#addressError').fadeIn('slow').html(data.res2);
			});
        }
    })
    .fail(function(){
        alert('Submit Failed ...');
    });
});
</script>
